# Generated by Django 5.2.14 on 2026-05-12 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('patients_enrolled', models.PositiveIntegerField(default=0)),
                ('high_risk_patients', models.PositiveIntegerField(default=0)),
                ('contacts_pending_screening', models.PositiveIntegerField(default=0)),
                ('contacts_screened', models.PositiveIntegerField(default=0)),
                ('tpt_started', models.PositiveIntegerField(default=0)),
                ('missed_follow_ups', models.PositiveIntegerField(default=0)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='facilities.facility')),
            ],
            options={
                'ordering': ['-date', 'facility__name'],
                'constraints': [models.UniqueConstraint(fields=('facility', 'date'), name='unique_facility_metric_day')],
            },
        ),
    ]
