# Generated by Django 5.2.14 on 2026-05-12 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter_type', models.CharField(choices=[('intake', 'Intake'), ('follow_up', 'Follow-up'), ('household_screening', 'Household screening'), ('adr_report', 'ADR report')], max_length=32)),
                ('occurred_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='patients.patient')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cough', models.BooleanField(default=False)),
                ('fever', models.BooleanField(default=False)),
                ('night_sweats', models.BooleanField(default=False)),
                ('weight_loss', models.BooleanField(default=False)),
                ('hiv_positive', models.BooleanField(default=False)),
                ('pregnant', models.BooleanField(default=False)),
                ('postpartum', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('sle_or_autoimmune', models.BooleanField(default=False)),
                ('ckd', models.BooleanField(default=False)),
                ('on_immunosuppressants', models.BooleanField(default=False)),
                ('previous_tb', models.BooleanField(default=False)),
                ('household_tb_contact', models.BooleanField(default=False)),
                ('crowded_housing', models.BooleanField(default=False)),
                ('poor_ventilation', models.BooleanField(default=False)),
                ('medication_history', models.JSONField(blank=True, default=dict)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intake', to='clinical.clinicalencounter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
