# Generated by Django 5.2.14 on 2026-05-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('facility_type', models.CharField(choices=[('dispensary', 'Dispensary'), ('health_centre', 'Health centre'), ('hospital', 'Hospital'), ('lab', 'Laboratory'), ('community_unit', 'Community unit')], max_length=32)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('sub_county', models.CharField(blank=True, max_length=100)),
                ('ward', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'facilities',
                'ordering': ['name'],
            },
        ),
    ]
