# Generated by Django 5.2.14 on 2026-05-12 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('given_name', models.CharField(max_length=150)),
                ('family_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('intersex', 'Intersex'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('national_id_hash', models.CharField(blank=True, max_length=128)),
                ('enrollment_source', models.CharField(choices=[('art_clinic', 'ART clinic'), ('anc', 'Antenatal care'), ('dispensary', 'Dispensary'), ('community', 'Community'), ('self_referral', 'Self-referral'), ('lab', 'Laboratory')], default='dispensary', max_length=32)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('consent_recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_consents_recorded', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='facilities.facility')),
            ],
            options={
                'ordering': ['family_name', 'given_name'],
            },
        ),
    ]
